#!/bin/bash

device="/dev/ttyUSB3"

builds_root="/home/geoff/projects/96boards/hikey/builds.96boards.org"

fastboot_build="15.06"

#uefi_build="46" # output on ttyAMA0
uefi_build="75" # output on ttyAMA3

debian_version="20150929-354"
debian_build=${debian_version##*-}

uefi_path=${uefi_path:-"${builds_root}/snapshots/hikey/linaro/uefi/${uefi_build}"}
fastboot_path=${fastboot_path:-"${builds_root}/releases/hikey/linaro/binaries/${fastboot_build}"}

_debian_path="${builds_root}/snapshots/hikey/linaro/debian/${debian_build}"

fastboot_boot_image="${_debian_path}/boot-fat.emmc.img"
uefi_boot_image="${_debian_path}/boot-fat.uefi.img"

system_image=${system_image:-"${_debian_path}/hikey-jessie_developer_${debian_version}.emmc.img"}
